"""add inventory sale

Revision ID: 37f07db72bfa
Revises: be55c430a792
Create Date: 2026-09-24 22:45:10.782085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f07db72bfa'
down_revision: Union[str, Sequence[str], None] = 'be55c430a792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres enum values can't be added via autogenerate — hand-written.
    # The existing labels are the Python Enum's member NAMES, not .value
    # ('COLLECTION', not 'collection' — see 723deff43d87_initial_schema.py),
    # so this must match that: 'SALE'. Safe inside this transaction since no
    # row uses it until a later one.
    op.execute("ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'SALE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_point_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sold_to', sa.String(length=255), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_point.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('inventory_sale')
    # Postgres has no DROP VALUE for enums; 'sale' is left in movement_type
    # unused, which is harmless (same tradeoff any enum-add migration makes).
