"""add partners, buyer orders, and collaborative collections

Revision ID: 9045fb2b7440
Revises: cd77c54ec167
Create Date: 2026-09-30 14:49:42.734811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9045fb2b7440'
down_revision: Union[str, Sequence[str], None] = 'cd77c54ec167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buyer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone', sa.String(length=30), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_dispatched', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PAID', 'PARTIALLY_DISPATCHED', 'FULFILLED', 'CANCELLED', name='buyer_order_status'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_order_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    # create_type=False: the 'payment_method' enum type already exists —
    # created by the original `payment` table's migration.
    sa.Column('method', postgresql.ENUM('MPESA', 'CASH', name='payment_method', create_type=False), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_order.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('collection_transaction', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.alter_column('collection_transaction', 'material_rate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_collection_transaction_partner_id_partner', 'collection_transaction', 'partner', ['partner_id'], ['id'])
    op.add_column('inventory_sale', sa.Column('buyer_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_inventory_sale_buyer_order_id_buyer_order', 'inventory_sale', 'buyer_order', ['buyer_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inventory_sale_buyer_order_id_buyer_order', 'inventory_sale', type_='foreignkey')
    op.drop_column('inventory_sale', 'buyer_order_id')
    op.drop_constraint('fk_collection_transaction_partner_id_partner', 'collection_transaction', type_='foreignkey')
    op.alter_column('collection_transaction', 'material_rate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('collection_transaction', 'partner_id')
    op.drop_table('buyer_order_payment')
    op.drop_table('buyer_order')
    op.drop_table('partner')
    # ### end Alembic commands ###
